doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Lms\Resource:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Resource/Entity'
                prefix: 'Lms\Resource\Entity'
                alias: Lms\Resource

            Lms\Storage:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Storage/Entity'
                prefix: 'Lms\Storage\Entity'
                alias: Lms\Storage

